name: Recolector de Datos de Tráfico

off:
  schedule:
    # Ejecuta cada 20 minutos
    - cron: '*/20 * * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Ejecutar el script de recolección
        # Pasa el Secreto de GitHub al script
        env:
          TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}
        run: python data_collector.py

      - name: Hacer commit y push del CSV
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'actions@github.com'
          git add data_historico.csv
          # Solo hace commit si el archivo CSV cambió
          git commit -m "DATA: Actualización automática de datos de tráfico" || echo "No hay cambios en los datos"
          git push
